fix: indefinite "submitted_at" in eeoc endpoint
JustEdro/tap-greenhouse pull request #4
Opened 2021-03-22 11:01 UTC by ricardoatsouza

The root of the problem comes from the HarvestAPI behavior: once a url in the format `?submitted_at=<date>` is sent, the returned url contains `?submitted_at=<date>&submitted_at=<date>` and this continues indefinitely.

The behavior can be correct, though, in the library. A PR was [created for it](https://github.com/Radico/tap-kit/pull/9). However, given that the repo is not very active, the same change was applied in the master branch of [its fork](https://github.com/ricardoatsouza/tap-kit/commit/758353629971b9b2a5fcc12c699383f856a094f8).

This PR is using the version with the correction, corrects the parameter name in the catalog and adds a `.gitignore` file.

2021-03-23 06:14 UTC, JustEdro commented on setup.py
> +        "tap-kit @ git+https://github.com/ricardoatsouza/tap-kit.git@758353629971b9b2a5fcc12c699383f856a094f8"
Please move to the org

2021-03-23 06:15 UTC, JustEdro requested changes
Please move custom dependencies to the organization

2021-03-23 15:46 UTC, ricardoatsouza commented on setup.py
> +        "tap-kit @ git+https://github.com/ricardoatsouza/tap-kit.git@758353629971b9b2a5fcc12c699383f856a094f8"
Fair enough. Changed in cc9172c.

2021-03-24 08:38 UTC, JustEdro approved these changes

2021-03-24 12:37 UTC, merged